//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_FLOOR2                      164
#define IDB_FLOOR1                      167
#define IDB_GRASS                       176
#define IDB_GRASS1                      176
#define IDB_GRASS2                      177
#define IDB_PAGE1                       184
#define IDB_PAGE2                       186
#define IDB_MAP_FINAL                   188
#define IDB_BITMAP6                     189
#define IDB_APU_FRONT1                  190
#define IDB_APU_RIGHT1                  190
#define IDB_APU_FRONT2                  191
#define IDB_APU_RIGHT2                  191
#define IDB_APU_FRONT3                  192
#define IDB_APU_RIGHT3                  192
#define IDB_APU_FRONT4                  193
#define IDB_APU_RIGHT4                  193
#define IDB_APU_BACK1                   194
#define IDB_APU_LEFT1                   194
#define IDB_APU_BACK2                   195
#define IDB_APU_LEFT2                   195
#define IDB_APU_BACK3                   196
#define IDB_APU_LEFT3                   196
#define IDB_APU_BACK4                   197
#define IDB_APU_LEFT4                   197
#define IDB_APU_DOWN1                   198
#define IDB_APU_DOWN2                   199
#define IDB_APU_DOWN3                   200
#define IDB_APU_DOWN4                   201
#define IDB_APU_UP1                     202
#define IDB_APU_UP2                     203
#define IDB_APU_UP3                     204
#define IDB_BITMAP5                     205
#define IDB_APU_UP4                     205
#define IDB_BITMAP7                     206
#define IDB_TREE                        206
#define IDB_TREE1                       206
#define IDB_FIGHT_UP1                   207
#define IDB_FIGHT_UP2                   208
#define IDB_FIGHT_UP3                   209
#define IDB_FIGHT_DOWN1                 210
#define IDB_FIGHT_DOWN2                 211
#define IDB_FIGHT_DOWN3                 212
#define IDB_FIGHT_BACK1                 213
#define IDB_FIGHT_BACK2                 214
#define IDB_FIGHT_BACK3                 215
#define IDB_FIGHT_FRONT1                216
#define IDB_FIGHT_FRONT2                217
#define IDB_BITMAP9                     218
#define IDB_BUTTON_BEGIN1               226
#define IDB_BUTTON_BEGIN2               227
#define IDB_APU_DOWN5                   229
#define IDB_BALLOON1                    230
#define IDB_BALLOON2                    231
#define IDB_BALLOON3                    232
#define IDB_BALLOON4                    233
#define IDB_BALLOON5                    234
#define IDB_BALLOON_DIE1                235
#define IDB_BALLOON_DIE2                236
#define IDB_BALLOON_DIE3                237
#define IDB_APU_LEFT5                   238
#define IDB_APU_UP5                     239
#define IDB_BITMAP8                     240
#define IDB_APU_RIGHT5                  240
#define IDB_FORK                        241
#define IDB_APU_LOSE1                   245
#define IDB_APU_LOSE2                   246
#define IDB_APU_LOSE3                   247
#define IDB_APU_LOSE4                   248
#define IDB_APU_LOSE5                   249
#define IDB_APU_LOSE6                   250
#define IDB_APU_RELIVE1                 251
#define IDB_APU_RELIVE2                 252
#define IDB_APU_RELIVE3                 253
#define IDB_APU_RELIVE4                 254
#define IDB_APU_RELIVE5                 255
#define IDB_FIGHT_UP4                   257
#define IDB_FIGHT_DOWN4                 259
#define IDB_FIGHT_LEFT1                 260
#define IDB_FIGHT_LEFT2                 261
#define IDB_FIGHT_LEFT3                 262
#define IDB_FIGHT_LEFT4                 263
#define IDB_FIGHT_RIGHT1                267
#define IDB_FIGHT_RIGHT2                268
#define IDB_FIGHT_RIGHT3                269
#define IDB_FIGHT_RIGHT4                270
#define IDB_TREE2                       271
#define IDB_GRASS3                      272
#define IDB_GRASS4                      273
#define IDB_TREE3                       274
#define IDB_WALL1                       275
#define IDB_WALL2                       277
#define IDB_BEGIN_PAGE1                 283
#define IDB_BEGIN_PAGE2                 284
#define IDB_LEVEL1                      285
#define IDB_LEVEL2                      286
#define IDB_LEVEL3                      287
#define IDB_BITMAP3                     288
#define IDB_LEVEL_PAGE                  288
#define IDB_BRICK1                      290
#define IDB_TURF                        291
#define IDB_APU_SUCCESS1                292
#define IDB_APU_SUCCESS2                293
#define IDB_APU_SUCCESS3                294
#define IDB_APU_SUCCESS4                295
#define IDB_APU_SUCCESS5                296
#define IDB_BRICK2                      297
#define IDB_BRICK4                      299
#define IDB_BRICK3                      300
#define IDB_FLOOR                       301
#define IDB_WALL3                       302
#define IDB_WALL4                       303
#define IDB_TREE4                       304
#define IDB_TREE5                       305
#define IDB_TREE6                       306
#define IDB_BRICK5                      307
#define IDB_BRICK6                      308
#define IDB_BITMAP4                     309
#define IDB_EXPLINATION                 309
#define IDB_ABOUT_PAGE                  311
#define IDB_BUTTON_EXPLAIN              313
#define IDB_EXPLAIN_PAGE                314
#define IDB_BUTTON_BACK                 315
#define IDB_BUTTON_ABOUTUS              319
#define IDB_CLAW1                       320
#define IDB_CLAW2                       321
#define IDB_CLAW3                       322
#define IDB_CLAW4                       323
#define IDB_CLAW5                       324
#define IDB_CLAW6                       325
#define IDB_CLAW7                       326
#define IDB_SPIKE1                      327
#define IDB_SPIKE2                      328
#define IDB_SPIKE3                      329
#define IDB_SPIKE4                      330
#define IDB_SPIKE5                      331
#define IDB_SPIKE6                      332
#define IDB_SPIKE                       333
#define IDB_BAT1                        334
#define IDB_BAT2                        335
#define IDB_BAT3                        336
#define IDB_PUMPKIN_DOWN                337
#define IDB_PUMPKIN_LEFT                338
#define IDB_PUMPKIN_RIGHT               339
#define IDB_PUMPKIN_UP                  340
#define IDB_BAT_DIE1                    341
#define IDB_BAT_DIE2                    342
#define IDB_BAT_DIE3                    343
#define IDB_PUMPKIN_DIE1                344
#define IDB_PUMPKIN_DIE2                345
#define IDB_PUMPKIN_DIE3                346
#define IDB_BUTTON_MENU1                347
#define IDB_BUTTON_MENU2                348
#define IDB_BUTTON_HOME1                349
#define IDB_BITMAP10                    350
#define IDB_BUTTON_HOME2                350
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        351
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
